services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: nexpert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d nexpert
      interval: 5s
      timeout: 5s
      retries: 5
